<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Models/ErrorViewModel.fs" />
    <Compile Include="Controllers/HomeController.fs" />
    <Compile Include="Controllers/AuthController.fs" />
    <Compile Include="Services/ApiClient.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="9.0.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Economia Com História - Angola.Core\ECHA.Core.csproj" />
  </ItemGroup>

</Project>
