// <auto-generated />
using System;
using EconomiaComHistoria.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EconomiaComHistoria.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.BadgeConquistado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataConquista")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("BadgesConquistados");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.CategoriaForum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Icone")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasForum");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Conteudo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("ImagemCapa")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nivel")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Regiao")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Resumo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Tema")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Texto")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UrlMedia")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Visualizacoes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Conteudos");

                    b.HasDiscriminator().HasValue("Conteudo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.ConteudoFavorito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConteudoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAdicionado")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId");

                    b.HasIndex("ConteudoId", "UtilizadorId")
                        .IsUnique();

                    b.ToTable("ConteudosFavoritos");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.DecisaoModeracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDecisao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Decisao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ModeracaoId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ModeracaoId");

                    b.ToTable("DecisoesModeracao");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.DenunciaConteudo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ComentarioId")
                        .HasColumnType("int");

                    b.Property<int?>("ConteudoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataDenuncia")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DenuncianteId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("RespostaId")
                        .HasColumnType("int");

                    b.Property<int?>("TopicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComentarioId");

                    b.HasIndex("ConteudoId");

                    b.HasIndex("DenuncianteId");

                    b.HasIndex("RespostaId");

                    b.HasIndex("TopicoId");

                    b.ToTable("DenunciasConteudo");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Escola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoMEC")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Escolas");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.EventoGamificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("EventosGamificacao");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Moderacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ComentarioId")
                        .HasColumnType("int");

                    b.Property<int?>("ConteudoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ComentarioId");

                    b.HasIndex("ConteudoId");

                    b.ToTable("Moderacoes");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.ModuloProgresso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PercentagemCompleta")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId", "Tema")
                        .IsUnique();

                    b.ToTable("ModulosProgresso");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.OpcaoResposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Explicacao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsCorrecta")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PerguntaId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("PerguntaId");

                    b.ToTable("OpcoesRespostas");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Pergunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrdemAleatorizada")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<int>("TempoLimiteSegundos")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Perguntas");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.PlanoEstudo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("PlanosEstudo");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConteudoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NivelDificuldade")
                        .HasColumnType("int");

                    b.Property<int>("NumeroPerguntas")
                        .HasColumnType("int");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TempoPorPerguntaSegundos")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ConteudoId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Ranking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataSnapshot")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EscolaId")
                        .HasColumnType("int");

                    b.Property<int>("Periodo")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("int");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("Rankings");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Reacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ComentarioId")
                        .HasColumnType("int");

                    b.Property<int?>("ConteudoId")
                        .HasColumnType("int");

                    b.Property<int?>("RespostaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoReacao")
                        .HasColumnType("int");

                    b.Property<int?>("TopicoId")
                        .HasColumnType("int");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComentarioId");

                    b.HasIndex("ConteudoId");

                    b.HasIndex("RespostaId");

                    b.HasIndex("TopicoId");

                    b.HasIndex("UtilizadorId", "TopicoId", "RespostaId", "TipoReacao")
                        .IsUnique();

                    b.ToTable("Reacoes");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.RelatorioProgresso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("RelatoriosProgresso");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.RespostaForum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataEdicao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EstadoResposta")
                        .HasColumnType("int");

                    b.Property<int?>("RespostaPaiId")
                        .HasColumnType("int");

                    b.Property<int>("TopicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("EstadoResposta");

                    b.HasIndex("RespostaPaiId");

                    b.HasIndex("TopicoId");

                    b.ToTable("RespostasForum");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.RespostaPergunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrecta")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OpcaoRespostaId")
                        .HasColumnType("int");

                    b.Property<int>("PerguntaId")
                        .HasColumnType("int");

                    b.Property<int>("TempoRespostaMs")
                        .HasColumnType("int");

                    b.Property<int>("TentativaQuizId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OpcaoRespostaId");

                    b.HasIndex("PerguntaId");

                    b.HasIndex("TentativaQuizId");

                    b.ToTable("RespostasPerguntas");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.SessaoEstudo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("SessoesEstudo");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.TentativaQuiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("TentativasQuiz");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.TopicoForum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EstadoTopico")
                        .HasColumnType("int");

                    b.Property<string>("MotivoRejeicao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("TotalDenuncias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EstadoTopico");

                    b.ToTable("TopicosForum");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("EscolaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EscolaId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("EscolaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("PontosTotais")
                        .HasColumnType("int");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StreakAtual")
                        .HasColumnType("int");

                    b.Property<bool>("SuspensaoPermanente")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("SuspensoAte")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Telemovel")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int?>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EscolaId");

                    b.HasIndex("TurmaId");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.VisualizacaoConteudo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConteudoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVisualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId");

                    b.HasIndex("ConteudoId", "UtilizadorId")
                        .IsUnique();

                    b.ToTable("VisualizacoesConteudo");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.ConteudoJindungo", b =>
                {
                    b.HasBaseType("EconomiaComHistoria.Core.Entities.Conteudo");

                    b.Property<DateTime?>("DataHistorica")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Origem")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasDiscriminator().HasValue("ConteudoJindungo");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.BadgeConquistado", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Badge", "Badge")
                        .WithMany("BadgesConquistados")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EconomiaComHistoria.Core.Entities.Utilizador", "Utilizador")
                        .WithMany("BadgesConquistados")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Comentario", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Utilizador", "Autor")
                        .WithMany("Comentarios")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Conteudo", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Utilizador", "Autor")
                        .WithMany("Conteudos")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.ConteudoFavorito", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Conteudo", "Conteudo")
                        .WithMany("Favoritos")
                        .HasForeignKey("ConteudoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EconomiaComHistoria.Core.Entities.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conteudo");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.DecisaoModeracao", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Moderacao", "Moderacao")
                        .WithMany("Decisoes")
                        .HasForeignKey("ModeracaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moderacao");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.DenunciaConteudo", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Comentario", "Comentario")
                        .WithMany()
                        .HasForeignKey("ComentarioId");

                    b.HasOne("EconomiaComHistoria.Core.Entities.Conteudo", "Conteudo")
                        .WithMany()
                        .HasForeignKey("ConteudoId");

                    b.HasOne("EconomiaComHistoria.Core.Entities.Utilizador", "Denunciante")
                        .WithMany()
                        .HasForeignKey("DenuncianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EconomiaComHistoria.Core.Entities.RespostaForum", "Resposta")
                        .WithMany("Denuncias")
                        .HasForeignKey("RespostaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EconomiaComHistoria.Core.Entities.TopicoForum", "Topico")
                        .WithMany("Denuncias")
                        .HasForeignKey("TopicoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Comentario");

                    b.Navigation("Conteudo");

                    b.Navigation("Denunciante");

                    b.Navigation("Resposta");

                    b.Navigation("Topico");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.EventoGamificacao", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Utilizador", "Utilizador")
                        .WithMany("EventosGamificacao")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Moderacao", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Comentario", "Comentario")
                        .WithMany()
                        .HasForeignKey("ComentarioId");

                    b.HasOne("EconomiaComHistoria.Core.Entities.Conteudo", "Conteudo")
                        .WithMany()
                        .HasForeignKey("ConteudoId");

                    b.Navigation("Comentario");

                    b.Navigation("Conteudo");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.ModuloProgresso", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.OpcaoResposta", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Pergunta", "Pergunta")
                        .WithMany("Opcoes")
                        .HasForeignKey("PerguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pergunta");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Pergunta", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Quiz", "Quiz")
                        .WithMany("Perguntas")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.PlanoEstudo", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Utilizador", "Utilizador")
                        .WithMany("PlanosEstudo")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Quiz", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Conteudo", null)
                        .WithMany("Quizzes")
                        .HasForeignKey("ConteudoId");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Ranking", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Reacao", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Comentario", "Comentario")
                        .WithMany()
                        .HasForeignKey("ComentarioId");

                    b.HasOne("EconomiaComHistoria.Core.Entities.Conteudo", "Conteudo")
                        .WithMany()
                        .HasForeignKey("ConteudoId");

                    b.HasOne("EconomiaComHistoria.Core.Entities.RespostaForum", "Resposta")
                        .WithMany("Reacoes")
                        .HasForeignKey("RespostaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EconomiaComHistoria.Core.Entities.TopicoForum", "Topico")
                        .WithMany("Reacoes")
                        .HasForeignKey("TopicoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EconomiaComHistoria.Core.Entities.Utilizador", "Utilizador")
                        .WithMany("Reacoes")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comentario");

                    b.Navigation("Conteudo");

                    b.Navigation("Resposta");

                    b.Navigation("Topico");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.RelatorioProgresso", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Utilizador", "Utilizador")
                        .WithMany("RelatoriosProgresso")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.RespostaForum", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Utilizador", "Autor")
                        .WithMany("RespostasForum")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EconomiaComHistoria.Core.Entities.RespostaForum", "RespostaPai")
                        .WithMany("RespostasFilhas")
                        .HasForeignKey("RespostaPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EconomiaComHistoria.Core.Entities.TopicoForum", "Topico")
                        .WithMany("Respostas")
                        .HasForeignKey("TopicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("RespostaPai");

                    b.Navigation("Topico");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.RespostaPergunta", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.OpcaoResposta", "OpcaoResposta")
                        .WithMany()
                        .HasForeignKey("OpcaoRespostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EconomiaComHistoria.Core.Entities.Pergunta", "Pergunta")
                        .WithMany("Respostas")
                        .HasForeignKey("PerguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EconomiaComHistoria.Core.Entities.TentativaQuiz", "TentativaQuiz")
                        .WithMany("Respostas")
                        .HasForeignKey("TentativaQuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpcaoResposta");

                    b.Navigation("Pergunta");

                    b.Navigation("TentativaQuiz");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.SessaoEstudo", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Utilizador", "Utilizador")
                        .WithMany("SessoesEstudo")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.TentativaQuiz", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Quiz", "Quiz")
                        .WithMany("Tentativas")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EconomiaComHistoria.Core.Entities.Utilizador", "Utilizador")
                        .WithMany("TentativasQuiz")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.TopicoForum", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Utilizador", "Autor")
                        .WithMany("Topicos")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EconomiaComHistoria.Core.Entities.CategoriaForum", "Categoria")
                        .WithMany("Topicos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Turma", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Escola", "Escola")
                        .WithMany("Turmas")
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EconomiaComHistoria.Core.Entities.Utilizador", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId");

                    b.Navigation("Escola");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Utilizador", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Escola", "Escola")
                        .WithMany("Utilizadores")
                        .HasForeignKey("EscolaId");

                    b.HasOne("EconomiaComHistoria.Core.Entities.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId");

                    b.Navigation("Escola");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.VisualizacaoConteudo", b =>
                {
                    b.HasOne("EconomiaComHistoria.Core.Entities.Conteudo", "Conteudo")
                        .WithMany("Visualizacoes_Rastreamento")
                        .HasForeignKey("ConteudoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EconomiaComHistoria.Core.Entities.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conteudo");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Badge", b =>
                {
                    b.Navigation("BadgesConquistados");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.CategoriaForum", b =>
                {
                    b.Navigation("Topicos");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Conteudo", b =>
                {
                    b.Navigation("Favoritos");

                    b.Navigation("Quizzes");

                    b.Navigation("Visualizacoes_Rastreamento");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Escola", b =>
                {
                    b.Navigation("Turmas");

                    b.Navigation("Utilizadores");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Moderacao", b =>
                {
                    b.Navigation("Decisoes");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Pergunta", b =>
                {
                    b.Navigation("Opcoes");

                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Quiz", b =>
                {
                    b.Navigation("Perguntas");

                    b.Navigation("Tentativas");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.RespostaForum", b =>
                {
                    b.Navigation("Denuncias");

                    b.Navigation("Reacoes");

                    b.Navigation("RespostasFilhas");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.TentativaQuiz", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.TopicoForum", b =>
                {
                    b.Navigation("Denuncias");

                    b.Navigation("Reacoes");

                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("EconomiaComHistoria.Core.Entities.Utilizador", b =>
                {
                    b.Navigation("BadgesConquistados");

                    b.Navigation("Comentarios");

                    b.Navigation("Conteudos");

                    b.Navigation("EventosGamificacao");

                    b.Navigation("PlanosEstudo");

                    b.Navigation("Reacoes");

                    b.Navigation("RelatoriosProgresso");

                    b.Navigation("RespostasForum");

                    b.Navigation("SessoesEstudo");

                    b.Navigation("TentativasQuiz");

                    b.Navigation("Topicos");
                });
#pragma warning restore 612, 618
        }
    }
}
